sim_duration_m: 10
sim_time_step_m: .1

plot:
  output_prefix: "test"

  show_live: true

  show_comms: true

  plots:
    - "ESTIMATION"
    - "COMMUNICATION"
    - "GROUND_STATION_RESULTS"

  gifs:
    - "SATELLITE_SIMULATION"

comms:
  max_bandwidth: 1000000
  max_neighbors: 4
  max_range: 1000000
  min_range: 0

estimator: "FEDERATED"
plan_horizon_m: 1

raids:
  Taiwan:
    center: [33.5, 12.0, 0]
    extent: [3, 3, 3]
    initial_targs: 2
    spawn_rate: 0
    color: red
  Ukraine:
    center: [44.37, -15.45, 0]
    extent: [5, 12, 3]
    initial_targs: 3
    spawn_rate: 0
    color: yellow


sensors:
  SensorGreat:
    fov: 115
    # 0.1
    bearings_error: [0.115, 0.115]
  SensorGood:
    fov: 115
    # 1%
    bearings_error: [1.15, 1.15]
  SensorBad:
    fov: 115
    # 10%
    bearings_error: [11.5, 11.5]

fusion_satellites:
  Sat0:
    sensor: null
    orbit:
      altitude: 1000
      ecc: 0
      inc: 60
      raan: -45
      argp: 45
      nu: 1
    color: "#669900"

sensing_satellites:
  Sat1a:
    sensor: SensorGood
    orbit:
      altitude: 1000
      ecc: 0
      inc: 60
      raan: -45
      argp: 45
      nu: 0
    color: "#669900"
  Sat1b:
    sensor: SensorGood
    orbit:
      altitude: 1000
      ecc: 0
      inc: 60
      raan: -45
      argp: 30
      nu: 0
    color: "#66a3ff"
  Sat2a:
    sensor: SensorBad
    orbit:
      altitude: 1000
      ecc: 0
      inc: 120
      raan: 45
      argp: 52
      nu: 0
    color: "#9966ff"
  Sat2b:
    sensor: SensorBad
    orbit:
      altitude: 1000
      ecc: 0
      inc: 120
      raan: 45
      argp: 37
      nu: 0
    color: "#ffff33"

commanders_intent:
  0:
    1: 175
    2: 225
    3: 350
    4: 110
    5: 125

ground_stations:
  GS1:
    lat: 60
    lon: 10
    fov: 80
    comms_range: 10000
    color: "black"
