sim_duration_m: 10

plot:
  output_prefix: "test"

  show_env: false

  plot_groundStation_results: true
  plot_estimation: true
  plot_communication: true
  plot_et_network: true
  plot_uncertainty_ellipses: false

  gifs:
    - "SATELLITE_SIMULATION"
    - "DYNAMIC_COMMS"
